### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by lidashuang** [muzuiget/mare#2]
![image](https://cloud.githubusercontent.com/assets/612381/24034288/ae3765a4-0b2b-11e7-9f8d-777ff8b96154.png)

另外 没有mac版本，或者需要一个how to run的教程

**Comment by muzuiget** [comment]
云风发贴早了，那时我还没改好，现在已经修复了。

打包好的在 https://github.com/muzuiget/mare-runner 的 Release 页，Mac 下还没试过，不过应该和 Linux 差别不大。具体过程看 http://mare.ejoy.com/docs.html 的「开发」一节。

或者 https://github.com/muzuiget/mare-runner/blob/master/build.sh 这个从头到尾的打包脚本。

**Comment by lidashuang** [comment]
在本机跑了
![image](https://cloud.githubusercontent.com/assets/612381/24034926/394516f8-0b2e-11e7-9059-cfb0246191d7.png)
 这应该就可以了吧

**Comment by muzuiget** [comment]
对的
