### ISSUE TITLE
mare-devtools-frontend怎么用？

### ISSUE THREAD

**Issue by young40** [muzuiget/mare#5]
在Chrome中似乎无法以扩展加载?

**Comment by muzuiget** [comment]
不是 Chrome 扩展， 就是纯静态的 HTML 文件，直接用 HTTP 服务托管即可。就像你使用 bower 安装的模块一样，最新的代码里会安装[预先打包好的](https://github.com/muzuiget/mare/blob/d2593432ec3b41ebf3c567379fa8d336d809b22f/web/bower.json)。
