### ISSUE TITLE
自定义lua loader的问题

### ISSUE THREAD

**Issue by dingmingxin** [muzuiget/mare#6]
今天花了一天的时间把这个调试库嵌入到cocos2dx(v3.16)-lua的工程中去。
踩了一个坑。

关键代码
=======

mare/debugvm/rdaux/frame.lua
```lua
    return {
        file = frame.source,
        line = frame.currentline,
        func = name,
    }
```

具体原因
======

如果file 不是 ‘@’ 开头的，那么在浏览器inspector界面，加断点是没有效果的。

解释
===
这个frame 是通过lua的`debug.getinfo` 接口得来的，里面有个source字段，如果是通过`luaL_loadfile`加载的lua代码，那么source会自动的在文件名前加一个‘@’符号。如果是通过`luaL_loadbuffer`加载的lua代码，那么就不会自动添加‘@’符号。

由于cocos2dx-lua一般都是自定义loader，调用的是`luaL_loadbuffer`，导致`debug.getinfo`里的source这一项不是以'@'开头，那么就会出现上面所描述的问题。

希望后面看到的同学在自定义loader的时候，不要继续再踩这个坑了。定位这个问题花了我好几小时的时间。。。。

**Comment by muzuiget** [comment]
对的，那个 `source`，Lua 文档里说

> source: 创建这个函数的代码块的名字。 如果 source 以 '@' 打头， 指这个函数定义在一个文件中，而 '@' 之后的部分就是文件名。 若 source 以 '=' 打头， 剩余的部分由用户行为来决定如何表示源码。 其它的情况下，这个函数定义在一个字符串中， 而 source 正是那个字符串

所以用 `load()` 之类的方法动态读取代码，自定义加载器设置 `source` 行为和 `reuqire()` 不同时，其实相当于不同文件了，虽然在源码角度看，你觉得就是同一个文件。

没想到好的解决方法，毕竟你在 devtools 对文件某行下一个断点里，是不知道你会用什么方法加载这个文件。我建议你可以 hack 一下 lua-libs 里的源码，比如 [breakpoint.lua](https://github.com/muzuiget/mare/blob/v0.2.3/lua-libs/mare/common/shunts/breakpoint.lua#L16) 那个 `match_line()` 返回 `true` 就行了。而 step 变量包含了当前的指令环境，结构就是 [step.lua](https://github.com/muzuiget/mare/blob/v0.2.3/lua-libs/mare/debugvm/rdaux/step.lua) 这个文件。

**Comment by dingmingxin** [comment]
谢谢。
我是通过修改cocos2dx的loader跳过这个坑的，毕竟load_buffer的情况不多。
